### ISSUE TITLE
csshX not working on macOS High Sierra

### ISSUE THREAD

**Issue by dounokouno** [brockgr/csshx#89]
I upgraded macOS to macOS High Sierra, csshx not working.

![csshx_not_working mov](https://user-images.githubusercontent.com/215381/31224931-d434638c-aa0a-11e7-9ae5-a01ff5b9b2c5.gif)

**Comment by tomharrisonjr** [comment]
Same issue as @dounokouno -- looks like the windows are being turned into terminal tabs now.

**Comment by tomharrisonjr** [comment]
Followup: this behavior is a result of a new default in High Sierra -- revert to previous behavior by selecting System Prefs > Dock > Prefer tabs when opening documents: Manually (default may be "Always").  All fixed :-)

**Comment by dounokouno** [comment]
@tomharrisonjr Thank you for following up! I confirmed that it works as expected in my environment.
